spring.application.name=login-signin

spring.datasource.url=jdbc:postgresql://localhost:5432/JWT
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8080

# JPA Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



# SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vijay.gopi5051@gmail.com
spring.mail.password=tlpuhbjuhheroinz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true

